### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [goreil/padding-oracle#1]
### Description:

In the "padding-oracle/oracle.py" and "padding-oracle/generate.py", I have identified a security vulnerability about insecure cryptographic algorithm usage. AES-CBC with fixed or hardcode IV is vulnerable to the chosen-ciphertext attack. And "Random" package would generate predictable pseudo random number.

### Location:

https://github.com/goreil/padding-oracle/blob/main/oracle.py#L6

```python
__iv=b'\x07\xff@h\xf3\xde<D\n>\x92\x1b\x95*\xa8\xd6'
cipher = AES.new(key = __key, mode=AES.MODE_CBC, iv = iv)
```

https://github.com/goreil/padding-oracle/blob/main/generate.py#L8

``` python
random.seed(123)
```

### Reference

- CWE-330: Use of Insufficiently Random Values

### Recommendations

- Generate IV with cryptographic secure PRNG.

**Comment by goreil** [comment]
Thank you! 

This is an educational Repository for the purpose of implementing a cryptographic attack. Therefore it doesn't need to be secure itself.

I will close the issue.
